name: Check Spack dependencies for updates

on:
  schedule:
   - cron: '54 * * * *'
  workflow_dispatch:

jobs:
    deps:
      name:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout this repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: create build
          run: mkdir build
        - name: Checkout ports-of-call
          uses: actions/checkout@v2
          with:
            repository: lanl/ports-of-call
            path: build/ports-of-call
            fetch-depth: 0
        - name: copy over spack-repo/packages
          run: cp -R build/ports-of-call/spack-repo/packages/* spack-repo/packages/
        - name: is there a difference?
          run: git diff --exit-code --compact-summary
          id: no_change
        - name: create branch
          if: ${{ failure() && steps.no_change.conclusion == 'failure' }}
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git checkout -b update_spackages
            git add spack-repo
            git commit -m "spack updates"
            git push -f --set-upstream origin update_spackages
        - name: create pull request
          if: ${{ failure() && steps.no_change.conclusion == 'failure' }}
          run: gh pr create -B main -H update_spackages --title 'Update spackages' --body 'Created by Github action'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
